export const SLIDES = [
  {
    id: 1,
    label: "Home",
    topRight: "Innovate  |  Build  |  Transform",
    headline: "Welcome to",
    headlineAccent: "NEXGRAVISION",
    subheadline: "One Company • One Software • Endless Possibilities",
    description: "We are a forward-thinking software company, delivering innovative digital solutions that help businesses grow, work smarter, and create better experiences.",
    cta: "Let's Build Your Future",
    services: [
      { icon: "web", label: "Web Applications" },
      { icon: "mobile", label: "Mobile Apps" },
      { icon: "cloud", label: "Cloud Solutions" },
      { icon: "consulting", label: "IT Consulting" },
    ],
  },
  {
    id: 2,
    label: "Our Software",
    topRight: "Smart Software  |  Better Business",
    sectionTag: "OUR SOFTWARE",
    headline: "What We Give Our",
    headlineAccent: "Customers",
    description: "We build custom, scalable and secure software solutions that solve real problems. Our technology helps businesses grow, improve efficiency and stay ahead in a competitive world — today and for what's next.",
    features: [
      { icon: "code", title: "Custom Software Development", subtitle: "Tailored to your needs" },
      { icon: "cloud", title: "Cloud & Web Solutions", subtitle: "Secure & Scalable" },
      { icon: "mobile", title: "Mobile App Development", subtitle: "iOS & Android" },
      { icon: "design", title: "UI/UX Design", subtitle: "Simple, Beautiful, Effective" },
      { icon: "support", title: "Ongoing Support", subtitle: "Always with you" },
      { icon: "transform", title: "Digital Transformation", subtitle: "For a smarter tomorrow" },
    ],
    badges: [
      { label: "Grow Faster", subtitle: "Scalable Solutions" },
      { label: "Work Smarter", subtitle: "Automate & Save Time" },
      { label: "Secure & Reliable", subtitle: "Your Data, Our Priority" },
      { label: "Better Experience", subtitle: "For Your Customers" },
    ],
  },
  {
    id: 3,
    label: "Our Projects",
    topRight: "Real Projects  |  Happy Clients",
    sectionTag: "OUR BEST PROJECTS",
    headline: "Solutions We've Built",
    headlineAccent: "for a Smarter Tomorrow",
    description: "We create powerful, user-friendly and scalable software solutions for businesses of all sizes. Here are some of our featured projects:",
    projects: [
      {
        title: "Employee Management System",
        description: "Simplify HR processes with our smart and secure employee management system.",
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80",
      },
      {
        title: "Smart Business Card",
        description: "Create stunning digital business cards. Share your profile, services, portfolio and contact info with one simple link.",
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80",
      },
      {
        title: "E-commerce Platform",
        description: "Build your online store with secure, fast and feature-rich solutions.",
        image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=800&q=80",
      },
    ],
    services: [
      { icon: "web", label: "Web Applications" },
      { icon: "mobile", label: "Mobile Apps" },
      { icon: "design", label: "UI/UX Design" },
      { icon: "cloud", label: "Cloud Solutions" },
    ],
  },
  {
    id: 4,
    label: "Our Clients",
    topRight: "Trusted by Businesses Worldwide",
    sectionTag: "OUR CLIENTS",
    headline: "Our",
    headlineAccent: "Trusted Clients",
    description: "We are proud to work with amazing brands and organizations that believe in our vision and technology.",
    stats: [
      { value: "50+", label: "Happy Clients" },
      { value: "100+", label: "Projects Delivered" },
      { value: "5+", label: "Years of Experience" },
    ],
    clientLogos: [
      { name: "Infosys", color: "#007CC3" },
      { name: "HDFC Bank", color: "#004B8D" },
      { name: "TATA", color: "#1B365D" },
      { name: "TCS", color: "#1A4D8F" },
      { name: "Wipro", color: "#2A2A6B" },
      { name: "Reliance", color: "#D42A2A" },
      { name: "ICICI Bank", color: "#F37B21" },
      { name: "IBM", color: "#0530AD" },
    ],
  },
  {
    id: 5,
    label: "Thank You",
    headline: "Thank You!",
    subheadline: "For Your Time, Trust and Support",
    description: "We're excited about the opportunity to work with you and look forward to building something amazing together.",
    values: ["Innovate", "Build", "Transform"],
    cta: "Let's Create Something Great",
    contact: {
      email: "info@nexgravision.com",
      website: "www.nexgravision.com",
    },
  },
];
