export const SLIDES = [
  {
    id: 1,
    label: "Home",
    headline: "Innovative\nSoftware Solutions\nfor a Smarter Tomorrow",
    subheadline: "Technology That Transforms Ideas Into Business.",
    description: "We build modern web, mobile and cloud applications that help businesses grow, automate and stay ahead in the digital world.",
    cta: "Explore Our Work",
  },
  {
    id: 2,
    label: "Our Clients",
    headline: "Trusted by Leading Brands",
    description: "We are proud to work with these amazing organizations.",
  },
  {
    id: 3,
    label: "About Us",
    headline: "Building Digital\nSolutions with Passion",
    description: "NexGravision is a young and innovative software company focused on delivering high-quality, scalable and user-friendly digital products. We turn ideas into powerful solutions that create real value for businesses.",
    values: [
      { icon: "innovation", title: "Innovation\nDriven" },
      { icon: "client", title: "Client\nFocused" },
      { icon: "quality", title: "Quality\nFirst" },
      { icon: "support", title: "Long-Term\nSupport" },
    ],
  },
  {
    id: 4,
    label: "Our Services",
    headline: "What We Offer",
    description: "From concept to deployment, we provide end-to-end software solutions tailored to your needs.",
    services: [
      { id: "web", title: "Web Application\nDevelopment" },
      { id: "mobile", title: "Mobile Application\nDevelopment" },
      { id: "cloud", title: "Cloud & DevOps\nSolutions" },
      { id: "uiux", title: "UI/UX Design" },
      { id: "api", title: "API Integration" },
      { id: "support", title: "Maintenance & Support" },
    ],
  },
  {
    id: 5,
    label: "Our Tech Stack",
    headline: "Technologies We Use",
    description: "We work with modern and reliable technologies to build future-ready solutions.",
  },
  {
    id: 6,
    label: "Featured Projects",
    headline: "Our Latest Work",
    description: "We build solutions that are creative, functional and make an impact.",
    projects: [
      {
        title: "Crop Disease Detection",
        tags: "Java | JSP | MySQL",
        category: "Farmers' Help",
      },
      {
        title: "Nursing College Website",
        tags: "HTML | CSS | JS",
        category: "Educational Platform",
      },
      {
        title: "Sharada Consultant",
        tags: "HTML | CSS | JS",
        category: "Real Estate Website",
      },
    ],
  },
  {
    id: 7,
    label: "How It Works",
    headline: "Simple Process,\nPowerful Results",
    steps: [
      { num: "01", title: "Discuss\nYour Idea", desc: "Tell us what\nyou need" },
      { num: "02", title: "Plan & Design", desc: "We create a\nstrategy & design" },
      { num: "03", title: "Develop", desc: "Build with\nmodern tech" },
      { num: "04", title: "Launch & Support", desc: "Deploy and\nscale together" },
    ],
  },
  {
    id: 8,
    label: "Why Choose Us",
    headline: "Your Success\nIs Our Priority",
    reasons: [
      { id: "team", title: "Expert Team", desc: "Skilled developers &\ncreative minds" },
      { id: "time", title: "On-Time Delivery", desc: "We respect your time" },
      { id: "process", title: "Transparent Process", desc: "Clear communication\nat every step" },
      { id: "price", title: "Affordable Pricing", desc: "Quality solutions\nwithin your budget" },
    ],
  },
  {
    id: 9,
    label: "Testimonials",
    headline: "What Our Clients Say",
    testimonials: [
      {
        quote: "NexGravision delivered our project on time with excellent quality. Their team is professional and supportive.",
        name: "Priya Sharma",
        role: "Business Owner",
      },
      {
        quote: "The website they built for us is modern, fast and exactly what we needed. Highly recommended!",
        name: "Rahul Deshmukh",
        role: "Founder",
      },
      {
        quote: "Great communication, creative solutions and amazing support even after delivery.",
        name: "Sneha Kulkarni",
        role: "Client",
      },
    ],
  },
  {
    id: 10,
    label: "Our Process",
    headline: "From Idea to Impact",
    processSteps: [
      { num: "01", title: "Discover", desc: "Understand your goals & requirements" },
      { num: "02", title: "Design", desc: "Create wireframes & UI/UX designs" },
      { num: "03", title: "Develop", desc: "Build, test and ensure quality" },
      { num: "04", title: "Deploy", desc: "Launch and provide ongoing support" },
    ],
  },
  {
    id: 11,
    label: "Build for Every Platform",
    headline: "Web & Mobile Applications",
    features: [
      { id: "responsive", title: "Responsive\nDesign" },
      { id: "performance", title: "Fast\nPerformance" },
      { id: "user", title: "User\nFriendly" },
      { id: "scalable", title: "Scalable" },
    ],
  },
  {
    id: 12,
    label: "Our Team",
    headline: "Passionate. Skilled. Collaborative.",
    description: "A dedicated team of developers, designers and problem solvers working together to bring your ideas to life.",
    team: [
      { name: "Sayali Patil", role: "Frontend Developer" },
      { name: "Anant Patil", role: "Backend Developer" },
      { name: "Sneha More", role: "UI/UX Designer" },
      { name: "Rohit Deshmukh", role: "Full Stack Developer" },
    ],
  },
  {
    id: 13,
    label: "Get In Touch",
    headline: "Let's Build Something Great",
    description: "Have a project in mind?\nWe'd love to hear from you.",
    contact: {
      phone: "+91 98765 43210",
      email: "info@nexgravision.com",
      address: "Sangli, Maharashtra, India",
    },
  },
  {
    id: 14,
    label: "Our Mission & Vision",
    headline: "What Drives Us",
    mission: {
      title: "Our Mission",
      description: "To deliver innovative and reliable software solutions that empower businesses and individuals to achieve more.",
    },
    vision: {
      title: "Our Vision",
      description: "To become a trusted global technology partner known for quality, innovation and customer satisfaction.",
    },
  },
  {
    id: 15,
    label: "Our Impact",
    headline: "Numbers That Speak",
    stats: [
      { number: "50+", label: "Happy Clients" },
      { number: "100+", label: "Projects Delivered" },
      { number: "5+", label: "Years of Experience" },
      { number: "100%", label: "Client Satisfaction" },
    ],
  },
  {
    id: 16,
    label: "Footer",
    headline: "NexGravision",
    tagline: "Ideas to Intelligent Solutions",
    description: "Let's build something amazing together.\nYour Vision • Our Technology • Success.",
    quickLinks: ["Home", "About", "Services", "Projects", "Contact"],
    services: ["Web Development", "Mobile Apps", "Cloud & DevOps", "UI/UX Design", "API Integration"],
    contactInfo: {
      phone: "+91 98765 43210",
      email: "info@nexgravision.com",
      address: "Sangli, Maharashtra, India",
    },
  },
  {
    id: 17,
    label: "Thank You",
    headline: "Thank You!",
    subheadline: "Let's Build the Future Together",
  },
];
