export const SLIDES = [
  {
    id: 1,
    label: "Home",
    topRight: "Innovate  |  Engineer  |  Elevate",
    headline: "Step Into",
    headlineAccent: "NEXGRAVISION",
    subheadline: "One Vision • One Platform • Unlimited Momentum",
    description: "We are a modern software company crafting intelligent digital products that help ambitious teams scale faster, operate cleaner and deliver experiences customers remember.",
    cta: "Start Building With Us",
    services: [
      { icon: "web", label: "Web Platforms" },
      { icon: "mobile", label: "Mobile Products" },
      { icon: "cloud", label: "Cloud Systems" },
      { icon: "consulting", label: "Tech Advisory" },
    ],
  },
  {
    id: 2,
    label: "Our Software",
    topRight: "Precision Software  |  Peak Performance",
    sectionTag: "OUR SOFTWARE",
    headline: "Built to Power Your",
    headlineAccent: "Next Chapter",
    description: "We engineer custom, secure and future-ready software that turns complex business problems into simple, high-performing digital experiences — ready for what is next.",
    features: [
      { icon: "code", title: "Custom Software", subtitle: "Designed around your goals" },
      { icon: "cloud", title: "Cloud & Web Systems", subtitle: "Secure. Scalable. Reliable." },
      { icon: "mobile", title: "Mobile Applications", subtitle: "Native and cross-platform" },
      { icon: "design", title: "UI/UX Design", subtitle: "Clear, elegant, intuitive" },
      { icon: "support", title: "Always-On Support", subtitle: "We stay after launch" },
      { icon: "transform", title: "Digital Transformation", subtitle: "Built for tomorrow" },
    ],
    badges: [
      { label: "Scale Confidently", subtitle: "Architecture that grows with you" },
      { label: "Work Faster", subtitle: "Automate the busywork" },
      { label: "Stay Protected", subtitle: "Security at every layer" },
      { label: "Delight Users", subtitle: "Experiences that convert" },
    ],
  },
  {
    id: 3,
    label: "Our Projects",
    topRight: "Proven Delivery  |  Real Results",
    sectionTag: "OUR WORK",
    headline: "Crafted Solutions for",
    headlineAccent: "Modern Business",
    description: "From HR platforms to fleet intelligence, we ship software that solves real operational challenges. Explore the products behind our client success stories.",
    projects: [
      {
        id: "employee-management",
        title: "Employee Management System",
        tagline: "Workforce clarity, delivered in one secure platform",
        category: "Enterprise HR Software",
        client: "Growing Enterprises & Mid-Sized Teams",
        year: "2024",
        duration: "12 Weeks",
        description: "A modern HR platform that unifies employee records, attendance, payroll workflows and leave management.",
        overview:
          "A complete people-operations suite that digitises every core HR workflow — employee records, attendance, payroll readiness and leave management — giving leadership one trusted source of truth for the entire workforce.",
        challenge:
          "HR teams were buried in spreadsheets, manual registers and disconnected tools. Attendance errors, delayed payroll and zero visibility over leave balances slowed decisions and created real compliance risk.",
        solution:
          "We built a role-based people platform with automated attendance capture, payroll-ready reporting, self-service leave requests and live HR analytics — all inside one secure web application.",
        features: [
          "Employee Profiles & Records",
          "Attendance Tracking",
          "Payroll Automation",
          "Leave Management",
          "Role-Based Access",
          "HR Analytics Dashboard",
        ],
        techStack: ["React", "Node.js", "MongoDB", "Express.js"],
        results: [
          { value: "40%", label: "Faster HR Operations" },
          { value: "100%", label: "Paperless Employee Records" },
          { value: "3x", label: "Quicker Payroll Reporting" },
        ],
        highlights: [
          "Self-service portal for employees and managers",
          "Audit-ready attendance and payroll exports",
          "Enterprise-grade access controls for HR data",
        ],
        image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80",
        accent: "#00B4D8",
      },
      {
        id: "smart-business-card",
        title: "Smart Business Card",
        tagline: "Your entire brand, captured in a single shareable link",
        category: "Digital Identity Platform",
        client: "Professionals & Modern Businesses",
        year: "2024",
        duration: "8 Weeks",
        description: "Premium digital business cards with live profiles, portfolios, contact capture and instant QR sharing.",
        overview:
          "A polished digital identity product that transforms one link into a full brand experience — profiles, services, portfolio, lead capture and shareable cards built for how people network today.",
        challenge:
          "Paper cards disappear, dates quickly and never showcase a full portfolio. Businesses needed a way to share complete professional profiles instantly — on any device — without printing waste.",
        solution:
          "We designed a mobile-first digital card with premium templates, instant QR and link sharing, live profile updates, view analytics and one-tap contact saving — all managed from a simple dashboard.",
        features: [
          "Instant Link & QR Sharing",
          "Custom Brand Templates",
          "Profile & Portfolio Blocks",
          "Lead Capture Forms",
          "View Analytics",
          "Mobile-First Experience",
        ],
        techStack: ["React", "Next.js", "Node.js", "MongoDB"],
        results: [
          { value: "1", label: "Link Replaces 100+ Paper Cards" },
          { value: "2x", label: "Faster Professional Networking" },
          { value: "0", label: "Printing Waste" },
        ],
        highlights: [
          "Live profile updates without reprinting",
          "Share via QR code, WhatsApp or email",
          "Built-in lead capture for growing businesses",
        ],
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80",
        accent: "#38BDF8",
      },
      {
        id: "fuel-management",
        title: "Fuel Management System",
        tagline: "Real-time fuel intelligence for high-performance fleets",
        category: "Fleet Operations Software",
        client: "Logistics & Fleet Operators",
        year: "2024",
        duration: "14 Weeks",
        description: "Live fuel tracking, vehicle efficiency scoring and operational analytics for smarter fleet decisions.",
        overview:
          "A fleet fuel intelligence platform that tracks consumption in real time, surfaces hidden inefficiencies and converts raw fuel data into operational decisions — from vehicle-level monitoring to executive reports.",
        challenge:
          "Fleets were losing money to untracked fuel use, route waste and manual reporting. Managers had no live view of consumption, mileage or vehicle health across large multi-depot operations.",
        solution:
          "We engineered a real-time fuel platform with live consumption tracking, vehicle efficiency scoring, automated anomaly alerts, route-level analytics and role-based reporting for operations teams.",
        features: [
          "Real-Time Fuel Tracking",
          "Vehicle Efficiency Scoring",
          "Consumption Reports",
          "Fleet Alerts & Exceptions",
          "Route-Level Analytics",
          "Role-Based Controls",
        ],
        techStack: ["React", "Node.js", "MySQL", "AWS"],
        results: [
          { value: "25%", label: "Average Fuel Cost Savings" },
          { value: "Live", label: "Fleet Visibility" },
          { value: "100%", label: "Audit-Ready Reporting" },
        ],
        highlights: [
          "Early detection of fuel theft and leakage",
          "Automated daily and monthly operations reports",
          "Scalable across multi-vehicle, multi-depot fleets",
        ],
        image: "https://images.unsplash.com/photo-1545262810-77515befe149?auto=format&fit=crop&w=800&q=80",
        accent: "#7DD3FC",
      },
    ],
    services: [
      { icon: "web", label: "Web Platforms" },
      { icon: "mobile", label: "Mobile Products" },
      { icon: "design", label: "Product Design" },
      { icon: "cloud", label: "Cloud Systems" },
    ],
  },
  {
    id: 4,
    label: "Our Clients",
    topRight: "Chosen by Teams That Value Excellence",
    sectionTag: "OUR CLIENTS",
    headline: "Built on Trust with",
    headlineAccent: "Remarkable Partners",
    description: "We are proud to partner with ambitious brands and organisations that believe in our vision, our craft and our technology.",
    stats: [
      { value: "50+", label: "Happy Clients" },
      { value: "100+", label: "Projects Delivered" },
      { value: "5+", label: "Years of Excellence" },
    ],
    clientLogos: [
      { name: "Infosys", color: "#007CC3" },
      { name: "HDFC Bank", color: "#004B8D" },
      { name: "TATA", color: "#1B365D" },
      { name: "TCS", color: "#1A4D8F" },
      { name: "Wipro", color: "#2A2A6B" },
      { name: "Reliance", color: "#D42A2A" },
      { name: "ICICI Bank", color: "#F37B21" },
      { name: "IBM", color: "#0530AD" },
    ],
  },
  {
    id: 5,
    label: "Thank You",
    headline: "Thank You!",
    subheadline: "For Your Time, Trust and Belief",
    description: "We would love the opportunity to partner with you and engineer something extraordinary together.",
    values: ["Innovate", "Build", "Transform"],
    cta: "Let’s Create What’s Next",
    contact: {
      email: "info@nexgravision.com",
      website: "www.nexgravision.com",
    },
  },
];
